### PR TITLE
Added TimerEntity and completed some methods. Still needs work.

### PR DESCRIPTION
**Pull request by VictorYao17**
Added all components to TimerScreen but still needs to be reorganized. 
Completed methods in TimerEntity but still needs JavaDoc. 
Methods in other classes are partially done but still need to be tweaked for the timer to function.

### CODE REVIEW

**Comment by jahink17** [comment]
Thank you for documenting the stuff that need to be implemented! Just one thing -- make sure to have your package names follow the naming convention (pothole_case)

**Comment by VictorYao17** [comment]
I will update that on the next commit, thanks for the reminder.

**Review by m1k2l3 — COMMENTED** [review]
Looks good for now. Make sure to follow the correct packaging format.

**Review by AVLTG — CHANGES_REQUESTED** [review]
Good job on the Code! Everything looks good, however, just as Jahin said, be careful of the directory naming convention. Another thing I noticed is that although is that your version is off. You have the right JDK version, however, since you probably have multiple corretto-11 versions (11.0.17 or 11.0.16), the name of your JDK in your misc.xml file is incorrect. To edit this, go to file on the top of IntelliJ, select project structure, select the "corretto-11 (2)" that you have and rename it to remove the " (2)", and also edit your misc.xml file to make sure it lines up with the main version. Other than that, looks good to go

**Pull request closed without merging**
