### PR TITLE
Basic GUI with some method implementation

### PR DESCRIPTION
**Pull request by CanaLeung**
[OLD]
A basic GUI created where the user can navigate between the directory menu, start screen, break screen, shop screen, sell item screen, buy item screen and boss fight screen. The basics of each screen have been setup including all necessary buttons (with listeners, controllers and interactors) but only the navigation methods have been implemented. The new game button has been partially implemented (a new stats object can initialized).

//UPDATE!!
This branch is now more developed and includes working code for the main game:
- initiating new game files (and/or overwriting existing game files) if they don't exist or are invalid
- full story added to story panel

### CODE REVIEW

**Review by madelahn — COMMENTED** [review]
Hi Cana! Awesome job so far! Everything seems to work pretty well, and the code is pretty easy to read, considering how much of a struggle it was, haha.
Some things to quickly note:
- While this isn't necessary, I think setting up different frames for different menus will definitely help with making the different screens easier to read. 
- Also, I think adding some javadocs will really help with making this easier to read, as well.
- The naming conventions are also a bit questionable and informal for some of the buttons and panels.

Once we finish up some of our other features, we should have an easy time organizing our GUI to be more clean by the time of the final submission. Again, really good job!!

**Review by jfongli — APPROVED** [review]
Looking good so far! Here are a couple of things I noticed: 

- AttackPotion.java, etc:  Starting the param’s descriptions with “This is…” is a little too pedantic. I think you could skip to the description immediately instead- ex.  “Name of attack potion”.  

- Defensive.java has a typo. Instead of “enhanceDefence” shouldn’t it be “enhanceDefense”? Other files with this typo: 
      - StatsUser.java
      - StatsDisplayViewModel.java
      - StatsUserTest.java
      - StatsDisplayViewModelTest.java

Shouldn't Equipable.java be Equippable.java? Some other files, like Weapon.java, use the double p. 

Besides this, good job! Keep it up✨

**Comment by m1k2l3** [comment]
> Looking good so far! Here are a couple of things I noticed:
> 
> * AttackPotion.java, etc:  Starting the param’s descriptions with “This is…” is a little too pedantic. I think you could skip to the description immediately instead- ex.  “Name of attack potion”.
> * Defensive.java has a typo. Instead of “enhanceDefence” shouldn’t it be “enhanceDefense”? Other files with this typo:
>   - StatsUser.java
>   - StatsDisplayViewModel.java
>   - StatsUserTest.java
>   - StatsDisplayViewModelTest.java
> * Shouldn't Equipable.java be Equippable.java? Some other files, like Weapon.java, use the double p.
> 
> Sorry if I seem too nitpicky! But you might forget about this misspelling when working on this another day.
> 
> Besides this, good job! Keep it up✨

I have fixed the documentation on the inventory entities, but I did not quite understand your second statement. 
I think that Equipable is the correct word for describing the ability to equip equipment.

**Review by jahink17 — COMMENTED** [review]
Good job Cana! Just one thing - your ValidStats class constructor seems to require an ErrorPresenter as its argument. This is a problem, since the ValidStats class would need to be called by my update stats interactor and that would be mean to instantiate a new ValidStats in my interactor, the interactor would have to depend on the presenter. This is a violation of the dependency rule.

You can easily solve this by creating an output boundary which the presenter implements. My interactor can then depend on the output boundary, which is fine.

I guess another thing you could do is to have the interactor take in an instance of ValidStats as an argument to its constructor, and that way the instantiation of ValidStats could be left up to the Main class. I think I like the first idea better though.

**Comment by jfongli** [comment]
> I have fixed the documentation on the inventory entities, but I did not quite understand your second statement. I think that Equipable is the correct word for describing the ability to equip equipment. #32

It is the correct word, the only issue is that the spelling is incorrect- the correct spelling is "Equippable". Just a tiny detail. Hope this clears it up!

**Comment by m1k2l3** [comment]
> > I have fixed the documentation on the inventory entities, but I did not quite understand your second statement. I think that Equipable is the correct word for describing the ability to equip equipment. #32
> 
> 
> 
> It is the correct word, the only issue is that the spelling is incorrect- the correct spelling is "Equippable". Just a tiny detail. Hope this clears it up!
> 
> 
> 
> 

I looked over the internet and found that both form is acceptable.

**Review by jahink17 — APPROVED** [review]
Thanks Cana, I think it looks good!

**Review by m1k2l3 — APPROVED** [review]
Great job Cana!

**Review by madelahn — APPROVED** [review]
Hi Cana, everything looks great! Thanks for your hard work :)

**Review by jfongli — APPROVED** [review]
Thanks for your hard work! I think it looks great.

**Pull request merged**
