### PR TITLE
Finished the delete_inventory_item, display_inventory_item and equip_equipment usecases. Finished the Invetnroy screen, inventory entities and added an inventory initializer. 

### PR DESCRIPTION
**Pull request by m1k2l3**
Added Entities and an adder method for adding new items to the player and shop inventory file.

### CODE REVIEW

**Review by madelahn — APPROVED** [review]
It's looking good Max, well done!

**Review by jahink17 — CHANGES_REQUESTED** [review]
Looks good for now, but I'll have to take a look at how everything fits together to make sure we're following clean architecture -- note to myself (ping me if i forget lol). Just a few things: 

1. some of the packages have names like "add_item" -- is this a use case package? If so, please add "use_case" to the end of the package name.
2. it seems that some of your public methods don't have javadocs yet. make sure to add them! 

Thanks, Max.

**Comment by jahink17** [comment]
Also, start writing some tests!

**Comment by madelahn** [comment]
> Looks good for now, but I'll have to take a look at how everything fits together to make sure we're following clean architecture -- note to myself (ping me if i forget lol). Just a few things:
> 
> 1. some of the packages have names like "add_item" -- is this a use case package? If so, please add "use_case" to the end of the package name.

I don't think that "add_item" in particular is a use case package, but I agree with Jahin that there should be less ambiguity in the naming conventions when possible. Good eyes Jahin!

**Comment by m1k2l3** [comment]
I agree with you, I have finished the implementation of the delete_player_inventory_item and display_player_inventory use cases. I have documented all the classes and I have included an inventory initializer that will reset the inventory file.

**Review by m1k2l3 — COMMENTED** [review]
Finished the delete_inventory_item and display_inventory item use cases. @jahink17

**Pull request merged**
