### PR TITLE
Completed Boss Fight

### PR DESCRIPTION
**Pull request by AVLTG**
After creating all of the necessary files for boss_fight directory in use_cases in the #10 BossFight Branch, I created a sub-branch of GUI and worked on BossFIght inside of this new sub-branch  GUI-x-boss-fight in which I could implement BossFight using Stats as well as the GUI branch to display the fight, and to work out the necessary steps in order to create the fightStats.csv using stats.csv. Also made some edits to the BreakScreen to make fightStats.csv reset every boss fight, as well as a lot of edits to the FightBossScreen in order to get the numbers to dynamically update and changed the buttons to help with this. Furthermore, I also implemented what happens when the player either wins or loses combat (sent back to the break menu), however, still need to make changes to update the level after every win. I just need to figure out how to do that using clean architecture and SOLID principles. Lastly, I still, need to develop tests and javadocs, hence why I am creating this pull request as a Draft. Ignore current error on CurrentFightStatsTest.java as that is still also a work in progress. :D

### CODE REVIEW

**Review by VictorYao17 — APPROVED** [review]
Each implemented class related to the boss_fight use case look great. I do have a couple suggestions though. For creating mappings in the hashtable in the FightWinner class, you can create two lists with values that you want to map together at the same indexes. Then you can loop through each value in the list to create mappings between them. The second thing is to make sure you add JavaDocs to each class and method that you write. Usually it is a good idea to write the JavaDocs while you are writing the methods so you will not be confused later and will not forget how the code works. Make sure to write tests for your methods as well.

**Review by madelahn — DISMISSED** [review]
Looks good Amirali, good job!

**Review by VictorYao17 — DISMISSED** [review]
Great implementation Amirali, I don't see any issues.

**Review by jahink17 — DISMISSED** [review]
Thanks!

**Review by VictorYao17 — COMMENTED** [review]
Great implementation Amirali, I don't see any issues.

**Review by madelahn — APPROVED** [review]

**Review by VictorYao17 — APPROVED** [review]
Great implementation Amirali, I don't see any issues.

**Pull request merged**
