### PR TITLE
Created skeleton for stats display use case

### PR DESCRIPTION
**Pull request by jahink17**
Class names for the stats display use case. Other use cases to be added, and classes and interfaces need to be implemented.

### CODE REVIEW

**Review by AVLTG — APPROVED** [review]
Good Job!

**Review by madelahn — COMMENTED** [review]
All classes look good, just keep an eye on gradle since it seems like you added some files 👍

**Review by madelahn — APPROVED** [review]
Everything looks good!

**Review by VictorYao17 — APPROVED** [review]
All classes look good

**Pull request merged**
