### PR TITLE
Created Classes and Interfaces

### PR DESCRIPTION
**Pull request by AVLTG**

### CODE REVIEW

**Review by madelahn — COMMENTED** [review]
Everything looks good! 🧀

**Review by madelahn — DISMISSED** [review]
Make sure to fix the failing check once we start adding all the code :D looks great otherwise

**Review by jfongli — APPROVED** [review]
Nice

**Review by jahink17 — DISMISSED** [review]
Looks good.

**Review by jfongli — APPROVED** [review]
👍

**Review by jahink17 — APPROVED** [review]
Looks good.

**Review by madelahn — APPROVED** [review]

**Pull request merged**
